# Generated by Django 2.1.2 on 2019-04-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_auto_20190419_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='title',
            field=models.CharField(default='JEC', max_length=100),
        ),
    ]
