# Generated by Django 2.1.2 on 2019-04-18 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_eventinfo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
