# Generated by Django 2.1.2 on 2019-04-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0005_auto_20190419_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinfo',
            old_name='profile_pic',
            new_name='event_pic',
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='description',
            field=models.CharField(default='Normal', help_text='Enter description...', max_length=200),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='priority',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Normal', 'Normal')], default='Normal', max_length=80),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='title',
            field=models.CharField(help_text='Enter title...', max_length=100),
        ),
    ]
