# Generated by Django 2.1.2 on 2019-04-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0007_auto_20190419_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='Make_breaking_news',
            field=models.CharField(blank=True, choices=[('Breaking news 1', 'Breaking news 1'), ('Breaking news 2', 'Breaking news 2'), ('Breaking news 3', 'Breaking news 3')], help_text='Only 3 breaking news is allowd if you want to add disable others', max_length=80, null=True),
        ),
    ]
