# Generated by Django 2.1.2 on 2019-04-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0008_auto_20190419_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='Make_breaking_news',
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='Grand_Event',
            field=models.CharField(blank=True, choices=[('Grand Event-1', 'Grand Event-1'), ('Grand Event-2', 'Grand Event-2'), ('Grand Event-3', 'Grand Event-3')], default=None, help_text='Only 3 breaking news is allowd if you want to add disable others', max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Trending', 'Trending')], help_text='Select Priority...', max_length=80),
        ),
    ]
