# Generated by Django 2.1.2 on 2019-04-19 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0009_auto_20190419_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='By',
            field=models.CharField(default='Sreerag CSE', help_text='Enter Author,Department...', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Trending', 'Trending')], help_text='Select Priority...', max_length=80),
        ),
    ]
