# Generated by Django 2.1.2 on 2019-04-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0010_auto_20190419_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='event_pic',
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='photos',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Trending', 'Trending')], help_text='Select Priority...', max_length=80),
        ),
    ]
