# Generated by Django 2.1.2 on 2019-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0013_auto_20190419_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinfo',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='thumbnail_folder'),
        ),
    ]
