# Generated by Django 2.1.2 on 2019-04-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0014_auto_20190419_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs'),
        ),
    ]
