# Generated by Django 2.1.2 on 2019-04-20 08:49

from django.db import migrations
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0015_auto_20190419_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='image',
            field=django_thumbs.db.models.ImageWithThumbsField(upload_to='images'),
        ),
    ]
