# Generated by Django 2.1.2 on 2019-04-20 08:57

from django.db import migrations
import django_thumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0016_auto_20190420_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='image',
            field=django_thumbs.fields.ImageThumbsField(sizes=({'code': 'avatar', 'resize': 'crop', 'wxh': '125x125'}, {'code': 'm', 'resize': 'scale', 'wxh': '640x480'}, {'code': '150', 'wxh': '150x150'}), upload_to='images'),
        ),
    ]
