# Generated by Django 2.1.2 on 2019-04-27 17:14

from django.db import migrations
import django_thumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0031_auto_20190421_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='Photo',
            field=django_thumbs.fields.ImageThumbsField(blank=True, default='11ffe044ec04e', help_text='Only 3 breaking news is allowd if you want to add disable others', sizes=({'code': 'gone', 'resize': 'crop', 'wxh': '725x573'}, {'code': 'gtwo', 'resize': 'crop', 'wxh': '725x274'}, {'code': 'normal', 'resize': 'crop', 'wxh': '350x238'}), upload_to='images'),
        ),
    ]
