# Generated by Django 2.1.2 on 2019-07-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0033_auto_20190706_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='Grand_Event',
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='Event_type',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Non-Academic', 'Non-Academic'), ('Class-Event', 'Class-Event')], default=None, help_text='Please mention type of event ', max_length=80, null=True),
        ),
    ]
