# Generated by Django 2.1 on 2019-08-23 18:50

from django.db import migrations
import django_thumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0034_auto_20190711_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='Photo',
            field=django_thumbs.fields.ImageThumbsField(blank=True, default='11ffe044ec04e', help_text='Upload *.jpg or *.jpeg images', sizes=({'code': 'normal', 'resize': 'crop', 'wxh': '350x238'},), upload_to='images'),
        ),
    ]
