# Generated by Django 2.1 on 2019-08-23 18:50

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Department',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Designation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Bus Codinator', 'Bus Codinator'), ('Professor', 'Professor'), ('Trade Instructor', 'Trade Instructor'), ('Office Assistant', 'Office Assistant'), ('Accountant', 'Accountant'), ('Office Manager', 'Office Manager'), ('Principal', 'Principal'), ('Secretary to Principal', 'Secretary to Principal'), ('Driver', 'Driver'), ('Manager', 'Manager'), ('Campus Head', 'Campus Head'), ('Asst. Manager', 'Asst. Manager'), ('Administrator', 'Administrator'), ('System Administrator', 'System Administrator'), ('Manager', 'Manager'), ('Chairman', 'Chairman'), ('Hostel Warden', 'Hostel Warden'), ('HOD', 'HOD'), ('', '')], max_length=268),
        ),
        migrations.AlterField(
            model_name='contact',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.department'),
        ),
    ]
