# Generated by Django 2.1.2 on 2019-04-17 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0002_auto_20190418_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_name', models.CharField(max_length=100, unique=True)),
                ('designation', models.CharField(max_length=100, unique=True)),
                ('comity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comity.comity')),
            ],
        ),
    ]
