# Generated by Django 2.1.2 on 2019-04-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comity', '0004_auto_20190418_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='jecc_code',
            field=models.CharField(default='JEC', max_length=100),
        ),
    ]
